INSERT INTO PERSON(FULL_NAME, DATE_OF_BIRTH, HEIGHT_IN_METERS) VALUES ('Lionel Messi', DATE '1987-06-24', 1.70);
INSERT INTO PERSON(FULL_NAME, DATE_OF_BIRTH, HEIGHT_IN_METERS) VALUES ('Christiano Ronaldo', DATE '1985-02-05', 1.87);
